from django.urls import path
from .views import (
    get_users,
    study_sessions,
    login_user,
    session_comments,
    session_delete,
    user_profile,
    user_profile_update,
    user_study_analytics,
    community_study_stats,
    user_connections,
    user_follow,
    messaging_conversations,
    messaging_conversation_detail,
    messaging_conversation_messages,
    session_like,
    notifications_list,
    notifications_mark_read,
    admin_users_overview,
    admin_user_manage,
)

urlpatterns = [
    path('', get_users),
    path('community-stats/', community_study_stats),
    path('<int:user_id>/study-analytics/', user_study_analytics),
    path('<int:user_id>/edit-profile/', user_profile_update),
    path('<int:user_id>/', user_profile),
    path('<int:user_id>/connections/', user_connections),
    path('<int:user_id>/follow/', user_follow),
    path('sessions/', study_sessions),
    path('sessions/<int:session_id>/comments/', session_comments),
    path('sessions/<int:session_id>/likes/', session_like),
    path('sessions/<int:session_id>/', session_delete),
    path('login/', login_user),  # 👈 IMPORTANT
    path('messages/conversations/', messaging_conversations),
    path('messages/conversations/<int:conversation_id>/', messaging_conversation_detail),
    path('messages/conversations/<int:conversation_id>/messages/', messaging_conversation_messages),
    path('notifications/', notifications_list),
    path('notifications/mark-read/', notifications_mark_read),
    path('admin/users-overview/', admin_users_overview),
    path('admin/users/<int:target_user_id>/', admin_user_manage),
]