# Generated by Django 6.0.4 on 2026-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
